sudo: required
language: ruby
rvm: 2.2
node_js: "0.10"
before_script:
  - npm install --prefix .github/pushnotification/node_modules .github/pushnotification/
  - gem install countries
  - gem install awesome_bot
  - sudo pip install json-spec
script:
  - awesome_bot contents.json -w skillsmatter,cfict,swiftbynorthwest
  - json validate --schema-file=.github/schema.json --document-file=contents.json
after_success:
  - ruby .github/convert.rb
  - node .github/pushnotification/sendpush
  - ./.github/deploy.sh
